name: Build and Test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  # Linux job
  linux:
    name: Linux (${{ matrix.compiler }}, ${{ matrix.config.name }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        compiler: [gcc, clang]
        config:
          - name: "Default"
            cmake_args: "-DFS_BUILD_EXAMPLES=ON -DFS_BUILD_TESTS=ON -DFS_BUILD_TOOLS=ON -DCMAKE_C_FLAGS=-Werror -DCMAKE_CXX_FLAGS=-Werror"
          - name: "Force C++"
            cmake_args: "-DFS_FORCE_CXX=ON -DFS_BUILD_EXAMPLES=ON -DFS_BUILD_TESTS=ON -DFS_BUILD_TOOLS=ON -DCMAKE_C_FLAGS=-Werror -DCMAKE_CXX_FLAGS=-Werror"
          - name: "Force C89"
            cmake_args: "-DFS_FORCE_C89=ON -DFS_BUILD_EXAMPLES=ON -DFS_BUILD_TESTS=ON -DFS_BUILD_TOOLS=ON -DCMAKE_C_FLAGS=-Werror -DCMAKE_CXX_FLAGS=-Werror"
          - name: "_FILE_OFFSET_BITS=32"
            cmake_args: "-DFS_BUILD_EXAMPLES=ON -DFS_BUILD_TESTS=ON -DFS_BUILD_TOOLS=ON -DCMAKE_C_FLAGS='-D_FILE_OFFSET_BITS=32 -Werror' -DCMAKE_CXX_FLAGS='-D_FILE_OFFSET_BITS=32 -Werror'"
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y cmake

      - name: Setup compiler
        run: |
          if [ "${{ matrix.compiler }}" = "clang" ]; then
            sudo apt-get install -y clang
            echo "CC=clang" >> $GITHUB_ENV
            echo "CXX=clang++" >> $GITHUB_ENV
          else
            echo "CC=gcc" >> $GITHUB_ENV
            echo "CXX=g++" >> $GITHUB_ENV
          fi

      - name: Configure CMake
        run: cmake -B build ${{ matrix.config.cmake_args }}

      - name: Build
        run: cmake --build build --parallel $(nproc)

      - name: Run tests
        run: cd build && ctest --output-on-failure --parallel $(nproc)

  # Windows job
  windows:
    name: Windows (${{ matrix.compiler }}, ${{ matrix.arch }}, ${{ matrix.config.name }})
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          # MSVC builds - both 32-bit and 64-bit
          - compiler: msvc
            arch: x64
            config: {name: "Default", cmake_args: "-DFS_BUILD_EXAMPLES=ON -DFS_BUILD_TESTS=ON -DFS_BUILD_TOOLS=ON"}
          - compiler: msvc
            arch: x64
            config: {name: "Force C++", cmake_args: "-DFS_FORCE_CXX=ON -DFS_BUILD_EXAMPLES=ON -DFS_BUILD_TESTS=ON -DFS_BUILD_TOOLS=ON"}
          - compiler: msvc
            arch: x64
            config: {name: "UNICODE", cmake_args: "-DFS_BUILD_EXAMPLES=ON -DFS_BUILD_TESTS=ON -DFS_BUILD_TOOLS=ON", c_flags: "-DUNICODE", cxx_flags: "-DUNICODE"}
          - compiler: msvc
            arch: x64
            config: {name: "Non-UNICODE", cmake_args: "-DFS_BUILD_EXAMPLES=ON -DFS_BUILD_TESTS=ON -DFS_BUILD_TOOLS=ON", c_flags: "-UMBCS", cxx_flags: "-UMBCS"}
          - compiler: msvc
            arch: x86
            config: {name: "Default", cmake_args: "-DFS_BUILD_EXAMPLES=ON -DFS_BUILD_TESTS=ON -DFS_BUILD_TOOLS=ON"}
          - compiler: msvc
            arch: x86
            config: {name: "Force C++", cmake_args: "-DFS_FORCE_CXX=ON -DFS_BUILD_EXAMPLES=ON -DFS_BUILD_TESTS=ON -DFS_BUILD_TOOLS=ON"}
          - compiler: msvc
            arch: x86
            config: {name: "UNICODE", cmake_args: "-DFS_BUILD_EXAMPLES=ON -DFS_BUILD_TESTS=ON -DFS_BUILD_TOOLS=ON", c_flags: "-DUNICODE", cxx_flags: "-DUNICODE"}
          - compiler: msvc
            arch: x86
            config: {name: "Non-UNICODE", cmake_args: "-DFS_BUILD_EXAMPLES=ON -DFS_BUILD_TESTS=ON -DFS_BUILD_TOOLS=ON", c_flags: "-UMBCS", cxx_flags: "-UMBCS"}
          # MinGW builds - 64-bit only
          - compiler: mingw
            arch: x64
            config: {name: "Default", cmake_args: "-DFS_BUILD_EXAMPLES=ON -DFS_BUILD_TESTS=ON -DFS_BUILD_TOOLS=ON"}
          - compiler: mingw
            arch: x64
            config: {name: "Force C++", cmake_args: "-DFS_FORCE_CXX=ON -DFS_BUILD_EXAMPLES=ON -DFS_BUILD_TESTS=ON -DFS_BUILD_TOOLS=ON"}
          - compiler: mingw
            arch: x64
            config: {name: "Force C89", cmake_args: "-DFS_FORCE_C89=ON -DFS_BUILD_EXAMPLES=ON -DFS_BUILD_TESTS=ON -DFS_BUILD_TOOLS=ON"}
          - compiler: mingw
            arch: x64
            config: {name: "UNICODE", cmake_args: "-DFS_BUILD_EXAMPLES=ON -DFS_BUILD_TESTS=ON -DFS_BUILD_TOOLS=ON", c_flags: "-DUNICODE", cxx_flags: "-DUNICODE"}
          - compiler: mingw
            arch: x64
            config: {name: "Non-UNICODE", cmake_args: "-DFS_BUILD_EXAMPLES=ON -DFS_BUILD_TESTS=ON -DFS_BUILD_TOOLS=ON", c_flags: "-UMBCS", cxx_flags: "-UMBCS"}
    steps:
      - uses: actions/checkout@v4

      - name: Setup MSVC
        if: matrix.compiler == 'msvc'
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: ${{ matrix.arch }}

      - name: Setup MinGW
        if: matrix.compiler == 'mingw'
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: >-
            mingw-w64-x86_64-gcc
            mingw-w64-x86_64-cmake
            mingw-w64-x86_64-make

      - name: Configure CMake (MSVC)
        if: matrix.compiler == 'msvc'
        run: cmake -B build ${{ matrix.config.cmake_args }} -A ${{ matrix.arch == 'x86' && 'Win32' || 'x64' }} -DCMAKE_C_FLAGS="/WX ${{ matrix.config.c_flags || '' }}" -DCMAKE_CXX_FLAGS="/WX ${{ matrix.config.cxx_flags || '' }}"

      - name: Configure CMake (MinGW)
        if: matrix.compiler == 'mingw'
        shell: msys2 {0}
        run: cmake -B build -G "MinGW Makefiles" ${{ matrix.config.cmake_args }} -DCMAKE_C_FLAGS="-Werror ${{ matrix.config.c_flags || '' }}" -DCMAKE_CXX_FLAGS="-Werror ${{ matrix.config.cxx_flags || '' }}"

      - name: Build (MSVC)
        if: matrix.compiler == 'msvc'
        run: cmake --build build --parallel --config Debug

      - name: Build (MinGW)
        if: matrix.compiler == 'mingw'
        shell: msys2 {0}
        run: cmake --build build --parallel

      - name: Run tests (MSVC)
        if: matrix.compiler == 'msvc'
        run: cd build && ctest --output-on-failure --parallel -C Debug

      - name: Run tests (MinGW)
        if: matrix.compiler == 'mingw'
        shell: msys2 {0}
        run: cd build && ctest --output-on-failure --parallel

  # macOS job
  macos:
    name: macOS (${{ matrix.config.name }})
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        config:
          - name: "Default"
            cmake_args: "-DFS_BUILD_EXAMPLES=ON -DFS_BUILD_TESTS=ON -DFS_BUILD_TOOLS=ON -DCMAKE_C_FLAGS=-Werror -DCMAKE_CXX_FLAGS=-Werror"
          - name: "Force C++"
            cmake_args: "-DFS_FORCE_CXX=ON -DFS_BUILD_EXAMPLES=ON -DFS_BUILD_TESTS=ON -DFS_BUILD_TOOLS=ON -DCMAKE_C_FLAGS=-Werror -DCMAKE_CXX_FLAGS=-Werror"
          - name: "Force C89"
            cmake_args: "-DFS_FORCE_C89=ON -DFS_BUILD_EXAMPLES=ON -DFS_BUILD_TESTS=ON -DFS_BUILD_TOOLS=ON -DCMAKE_C_FLAGS=-Werror -DCMAKE_CXX_FLAGS=-Werror"
          - name: "_FILE_OFFSET_BITS=32"
            cmake_args: "-DFS_BUILD_EXAMPLES=ON -DFS_BUILD_TESTS=ON -DFS_BUILD_TOOLS=ON -DCMAKE_C_FLAGS='-D_FILE_OFFSET_BITS=32 -Werror' -DCMAKE_CXX_FLAGS='-D_FILE_OFFSET_BITS=32 -Werror'"
    steps:
      - uses: actions/checkout@v4

      - name: Configure CMake
        run: cmake -B build ${{ matrix.config.cmake_args }}

      - name: Build
        run: cmake --build build --parallel $(sysctl -n hw.ncpu)

      - name: Run tests
        run: cd build && ctest --output-on-failure --parallel $(sysctl -n hw.ncpu)

  # Android job
  android:
    name: Android (${{ matrix.arch }}, ${{ matrix.config.name }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        arch: [arm64-v8a, armeabi-v7a, x86_64]
        config:
          - name: "Default"
            cmake_args: "-DFS_BUILD_EXAMPLES=ON -DFS_BUILD_TESTS=ON -DFS_BUILD_TOOLS=ON -DCMAKE_C_FLAGS=-Werror -DCMAKE_CXX_FLAGS=-Werror"
    steps:
      - uses: actions/checkout@v4
      - name: Setup Android NDK
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r25c
      - name: Configure CMake
        run: |
          TOOLCHAIN_FILE=$ANDROID_NDK_ROOT/build/cmake/android.toolchain.cmake
          cmake -B build \
            -DCMAKE_TOOLCHAIN_FILE=$TOOLCHAIN_FILE \
            -DANDROID_ABI=${{ matrix.arch }} \
            -DANDROID_PLATFORM=android-21 \
            ${{ matrix.config.cmake_args }}
      - name: Build
        run: cmake --build build --parallel $(nproc)

  # FreeBSD job
  freebsd:
    name: FreeBSD (${{ matrix.config.name }})
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        config:
          - {name: "Default", cmake_args: "-DFS_BUILD_EXAMPLES=ON -DFS_BUILD_TESTS=ON -DFS_BUILD_TOOLS=ON -DCMAKE_C_FLAGS=-Werror -DCMAKE_CXX_FLAGS=-Werror"}
          - {name: "_FILE_OFFSET_BITS=32", cmake_args: "-DFS_BUILD_EXAMPLES=ON -DFS_BUILD_TESTS=ON -DFS_BUILD_TOOLS=ON -DCMAKE_C_FLAGS='-D_FILE_OFFSET_BITS=32 -Werror' -DCMAKE_CXX_FLAGS='-D_FILE_OFFSET_BITS=32 -Werror'"}
    steps:
      - uses: actions/checkout@v4
      - name: Test on FreeBSD
        uses: vmactions/freebsd-vm@v1
        with:
          usesh: true
          prepare: |
            pkg install -y cmake
          run: |
            cmake -B build ${{ matrix.config.cmake_args }}
            cmake --build build --parallel $(sysctl -n hw.ncpu)
            cd build && ctest --output-on-failure --parallel $(sysctl -n hw.ncpu)

  # OpenBSD job
  openbsd:
    name: OpenBSD (${{ matrix.config.name }})
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        config:
          - {name: "Default", cmake_args: "-DFS_BUILD_EXAMPLES=ON -DFS_BUILD_TESTS=ON -DFS_BUILD_TOOLS=ON -DCMAKE_C_FLAGS=-Werror -DCMAKE_CXX_FLAGS=-Werror"}
          - {name: "_FILE_OFFSET_BITS=32", cmake_args: "-DFS_BUILD_EXAMPLES=ON -DFS_BUILD_TESTS=ON -DFS_BUILD_TOOLS=ON -DCMAKE_C_FLAGS='-D_FILE_OFFSET_BITS=32 -Werror' -DCMAKE_CXX_FLAGS='-D_FILE_OFFSET_BITS=32 -Werror'"}
    steps:
      - uses: actions/checkout@v4
      - name: Test on OpenBSD
        uses: vmactions/openbsd-vm@v1
        with:
          usesh: true
          prepare: |
            pkg_add cmake
          run: |
            cmake -B build ${{ matrix.config.cmake_args }}
            cmake --build build --parallel $(sysctl -n hw.ncpu)
            cd build && ctest --output-on-failure --parallel $(sysctl -n hw.ncpu)

  # NetBSD job
  netbsd:
    name: NetBSD (${{ matrix.config.name }})
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        config:
          - {name: "Default", cmake_args: "-DFS_BUILD_EXAMPLES=ON -DFS_BUILD_TESTS=ON -DFS_BUILD_TOOLS=ON -DCMAKE_C_FLAGS=-Werror -DCMAKE_CXX_FLAGS=-Werror"}
          - {name: "_FILE_OFFSET_BITS=32", cmake_args: "-DFS_BUILD_EXAMPLES=ON -DFS_BUILD_TESTS=ON -DFS_BUILD_TOOLS=ON -DCMAKE_C_FLAGS='-D_FILE_OFFSET_BITS=32 -Werror' -DCMAKE_CXX_FLAGS='-D_FILE_OFFSET_BITS=32 -Werror'"}
    steps:
      - uses: actions/checkout@v4
      - name: Test on NetBSD
        uses: vmactions/netbsd-vm@v1
        with:
          usesh: true
          prepare: |
            /usr/sbin/pkg_add cmake
          run: |
            cmake -B build ${{ matrix.config.cmake_args }}
            cmake --build build
            cd build && ctest --output-on-failure
